version: "3"

services:
    dockeruserclient:
    
        build: dockeruserclient/
            
        
        
        ports:
            - 5000:5000
            
    docker_testpy:
    
        build: docker_testpy/
            
            
                
        network_mode: host
   
        depends_on:
            - dockeruserclient
